export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const VALIDATE = 'VALIDATE';
export const LOGOUT = 'LOGOUT';
export const SET_AVATAR = 'SET_AVATAR';
export const GET_SLIDERS = 'GET_SLIDERS';
export const GET_LESSONS = 'GET_LESSONS';
export const SET_LESSONS = 'SET_LESSONS';
export const SET_LESSONS_LOADING = 'SET_LESSONS_LOADING';
export const REFRESH_LESSONS = 'REFRESH_LESSONS';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
export const CHANGE_CART_ITEM_COUNT = 'CHANGE_CART_ITEM_COUNT';
export const CHANGE_CHECKED_CART_ITEMS = 'CHANGE_CHECKED_CART_ITEMS';
export const SETTLE = 'SETTLE';